name: Update versions

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Fetch latest versions
        uses: nick-fields/retry@v4
        with:
          max_attempts: 5
          timeout_minutes: 10
          command: |
            set -uo pipefail
            PYTHON=$(git ls-remote --tags https://github.com/python/cpython.git/  \
              | awk -F/ '{print $3}' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
              | sed 's/^v//' | sort -V | tail -1)
            GCC=$(curl -s https://ftp.gnu.org/gnu/gcc/ \
              | grep -o 'gcc-[0-9]\+\.[0-9]\+\.[0-9]\+/' \
              | sed 's#gcc-##; s#/##' \
              | sort -V | tail -n 1)
            ZLIB=$(curl -s https://zlib.net/ \
              | grep -o 'zlib-[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?\.tar\.gz' \
              | sed 's/zlib-//; s/\.tar\.gz//' \
              | sort -V | tail -n 1)
            OPENSSL=$(git ls-remote --tags https://github.com/openssl/openssl \
              | awk -F/ '/[0-9]$/  && /openssl-/ && ! /-[a-z]/ {gsub("openssl-", ""); print $3}' \
              | sort -V | grep -Ev '^4' | tail -1)
            READLINE=$(curl -s https://ftp.gnu.org/gnu/readline/ \
              | grep -Eo 'readline-[0-9]+(\.[0-9]+)*\.tar\.gz' \
              | sed -E 's/readline-([0-9.]+)\.tar\.gz/\1/' \
              | sort -uV | tail -1)
            NCURSES=$(curl -s https://ftp.gnu.org/gnu/ncurses/ \
              | grep -Eo 'ncurses-[0-9]+(\.[0-9]+)*\.tar\.gz' \
              | sed -E 's/ncurses-([0-9.]+)\.tar\.gz/\1/' \
              | sort -uV | tail -1)
            LIBFFI=$(git ls-remote --tags https://github.com/libffi/libffi.git/  \
              | awk -F/ '{print $3}' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
              | sed 's/^v//' | sort -V | tail -1)
            BZIP2=$(git ls-remote --tags https://gitlab.com/bzip2/bzip2.git/ \
              | awk -F/ '{print $3}' | grep -E 'bzip2-[0-9]+\.[0-9]+\.[0-9]+$' \
              | sed 's/^bzip2-//' | sort -V | tail -n 1)
            XZ=$(git ls-remote --tags https://github.com/tukaani-project/xz.git/  \
              | awk -F/ '{print $3}' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
              | sed 's/^v//' | sort -V | tail -1)
  
            yq -i ".python= \"$PYTHON\"" versions.yaml
            yq -i ".gcc= \"$GCC\"" versions.yaml
            yq -i ".zlib= \"$ZLIB\"" versions.yaml
            yq -i ".openssl= \"$OPENSSL\"" versions.yaml
            yq -i ".readline= \"$READLINE\"" versions.yaml
            yq -i ".ncurses= \"$NCURSES\"" versions.yaml
            yq -i ".libffi= \"$LIBFFI\"" versions.yaml
            yq -i ".bzip2= \"$BZIP2\"" versions.yaml
            yq -i ".xz= \"$XZ\"" versions.yaml
            git diff versions.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update-versions
          delete-branch: true
          title: Update versions
          commit-message: Update versions
